### ISSUE TITLE
Encountered "Cannot read properties of undefined (reading 'typeAnnotation')" Error while Integrating Plugin into Project

### ISSUE THREAD

**Issue by kyle1an** [unplugin/unplugin-vue-tsx-auto-props#11]

**Comment by so1ve** [comment]
Thanks, nice catch!
I am pretty unfamiliar with babel AST, so the code is loooooooong and not robust. I'll try to improve.

**Comment by so1ve** [comment]
And thanks for your kind words - it is the first time that someone has used my project and send a pr to me(even a small one)
